from pathlib import Path
import json
import os
import pickle
import re
import string
import time
import warnings

import dagshub
import mlflow
import nltk
import pandas as pd
from dotenv import load_dotenv
from flask import Flask, render_template, request
from nltk import pos_tag
from nltk.corpus import stopwords, wordnet
from nltk.stem import WordNetLemmatizer
from prometheus_client import (
    CONTENT_TYPE_LATEST,
    CollectorRegistry,
    Counter,
    Histogram,
    generate_latest,
)

warnings.simplefilter("ignore", UserWarning)
warnings.filterwarnings("ignore")

BASE_DIR = Path(__file__).resolve().parent
REPO_ROOT = BASE_DIR.parent

# Load env from both current dir and repository root.
load_dotenv()
load_dotenv(REPO_ROOT / ".env")


def ensure_nltk_resources() -> None:
    """Ensure resources used in training-time preprocessing are available."""
    resource_checks = {
        "stopwords": lambda: stopwords.words("english"),
        "wordnet": lambda: wordnet.ensure_loaded(),
        "averaged_perceptron_tagger_eng": lambda: pos_tag(["sample"]),
    }

    for resource_name, checker in resource_checks.items():
        try:
            checker()
        except LookupError:
            nltk.download(resource_name, quiet=True)


def get_wordnet_pos(tag: str):
    if tag.startswith("J"):
        return wordnet.ADJ
    if tag.startswith("V"):
        return wordnet.VERB
    if tag.startswith("N"):
        return wordnet.NOUN
    if tag.startswith("R"):
        return wordnet.ADV
    return wordnet.NOUN


def clean_text(text: str, lemmatizer: WordNetLemmatizer, stop_words: set[str]) -> str:
    """Match src/data/data_preprocessing.py behavior for single-text inference."""
    text = str(text)
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = text.lower()
    text = re.sub(r"\d+", " ", text)
    text = re.sub(f"[{re.escape(string.punctuation)}]", " ", text)
    text = re.sub(r"[^a-z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    if not text:
        return ""

    tokens = [token for token in text.split() if token not in stop_words and len(token) > 1]
    if not tokens:
        return ""

    tagged_tokens = pos_tag(tokens)
    lemmatized_tokens = [
        lemmatizer.lemmatize(token, get_wordnet_pos(tag))
        for token, tag in tagged_tokens
    ]
    return " ".join(lemmatized_tokens)


def preprocess_input_text(text: str) -> str:
    lemmatizer = WordNetLemmatizer()
    stop_words = set(stopwords.words("english"))
    return clean_text(text, lemmatizer, stop_words)


def configure_tracking() -> None:
    """Configure MLflow tracking and optional DagsHub auth."""
    tracking_uri = os.getenv(
        "MLFLOW_TRACKING_URI",
        "https://dagshub.com/rinkudiwakar/capstone-Project-1.mlflow",
    )
    dagshub_token = os.getenv("CAPSTONE_TEST")
    repo_owner = os.getenv("DAGSHUB_REPO_OWNER", "rinkudiwakar")
    repo_name = os.getenv("DAGSHUB_REPO_NAME", "capstone-Project-1")

    if dagshub_token:
        os.environ["MLFLOW_TRACKING_USERNAME"] = dagshub_token
        os.environ["MLFLOW_TRACKING_PASSWORD"] = dagshub_token

        try:
            dagshub.init(repo_owner=repo_owner, repo_name=repo_name, mlflow=True)
        except Exception as exc:
            print(f"Warning: DagsHub init failed, continuing with tracking URI only. Error: {exc}")

    mlflow.set_tracking_uri(tracking_uri)


def get_latest_model_version(model_name: str):
    client = mlflow.MlflowClient()
    for stage in ("Production", "Staging", "None"):
        versions = client.get_latest_versions(model_name, stages=[stage])
        if versions:
            return versions[0].version
    return None


def get_latest_run_id() -> str | None:
    """Read latest run id from reports artifact generated by pipeline."""
    exp_info_path = REPO_ROOT / "reports" / "experiment_info.json"
    if not exp_info_path.exists():
        return None

    try:
        with open(exp_info_path, "r", encoding="utf-8") as f:
            payload = json.load(f)
        return payload.get("run_id")
    except Exception as exc:
        print(f"Warning: failed to parse {exp_info_path}: {exc}")
        return None


def load_pickle_from_mlflow_or_local(file_name: str, run_id: str | None):
    """Load preprocessing artifact from MLflow run first, local models/ as fallback."""
    if run_id:
        artifact_path = f"preprocessing/{file_name}"
        try:
            local_artifact = mlflow.artifacts.download_artifacts(
                run_id=run_id,
                artifact_path=artifact_path,
            )
            with open(local_artifact, "rb") as f:
                print(f"Loaded {file_name} from MLflow artifacts")
                return pickle.load(f)
        except Exception as exc:
            print(f"Warning: could not load {artifact_path} from MLflow run {run_id}: {exc}")

    local_path = REPO_ROOT / "models" / file_name
    if not local_path.exists():
        return None

    with open(local_path, "rb") as f:
        print(f"Loaded {file_name} from local path {local_path}")
        return pickle.load(f)


def load_serving_model():
    """Try MLflow registry first, then fallback to local pickle model."""
    model_name = os.getenv("MLFLOW_MODEL_NAME", "sentiment-classifier")

    try:
        model_version = get_latest_model_version(model_name)
        if model_version is not None:
            model_uri = f"models:/{model_name}/{model_version}"
            print(f"Fetching model from: {model_uri}")
            return mlflow.pyfunc.load_model(model_uri)
    except Exception as exc:
        print(f"Warning: failed to load model from MLflow registry: {exc}")

    local_model_path = REPO_ROOT / "models" / "model.pkl"
    if not local_model_path.exists():
        raise FileNotFoundError(f"Local fallback model not found at {local_model_path}")

    print(f"Using local model fallback: {local_model_path}")
    with open(local_model_path, "rb") as f:
        return pickle.load(f)


def transform_text_to_features(text: str) -> pd.DataFrame:
    """Apply feature engineering sequence used in training."""
    X = vectorizer.transform([text])
    feature_names = vectorizer.get_feature_names_out()

    if variance_selector is not None:
        X = variance_selector.transform(X)
        feature_names = feature_names[variance_selector.get_support()]

    if maxabs_scaler is not None:
        X = maxabs_scaler.transform(X)

    if select_k_best is not None:
        X = select_k_best.transform(X)
        feature_names = feature_names[select_k_best.get_support()]

    feature_values = X.toarray() if hasattr(X, "toarray") else X

    if hasattr(model, "feature_names_in_"):
        expected_columns = list(model.feature_names_in_)
        if len(expected_columns) == feature_values.shape[1]:
            return pd.DataFrame(feature_values, columns=expected_columns)

    return pd.DataFrame(feature_values, columns=[str(col) for col in feature_names])


ensure_nltk_resources()
configure_tracking()

run_id = get_latest_run_id()
model = load_serving_model()
vectorizer = load_pickle_from_mlflow_or_local("vectorizer.pkl", run_id)
variance_selector = load_pickle_from_mlflow_or_local("variance_selector.pkl", run_id)
maxabs_scaler = load_pickle_from_mlflow_or_local("maxabs_scaler.pkl", run_id)
select_k_best = load_pickle_from_mlflow_or_local("select_k_best.pkl", run_id)

if vectorizer is None:
    raise FileNotFoundError("vectorizer.pkl was not found in MLflow artifacts or local models directory")

# Initialize Flask app
app = Flask(__name__)

# Create a custom registry
registry = CollectorRegistry()

# Define custom metrics
REQUEST_COUNT = Counter(
    "app_request_count", "Total number of requests to the app", ["method", "endpoint"], registry=registry
)
REQUEST_LATENCY = Histogram(
    "app_request_latency_seconds", "Latency of requests in seconds", ["endpoint"], registry=registry
)
PREDICTION_COUNT = Counter(
    "model_prediction_count", "Count of predictions for each class", ["prediction"], registry=registry
)


@app.route("/")
def home():
    REQUEST_COUNT.labels(method="GET", endpoint="/").inc()
    start_time = time.time()
    response = render_template("index.html", result=None)
    REQUEST_LATENCY.labels(endpoint="/").observe(time.time() - start_time)
    return response


@app.route("/predict", methods=["POST"])
def predict():
    REQUEST_COUNT.labels(method="POST", endpoint="/predict").inc()
    start_time = time.time()

    raw_text = request.form["text"]
    text = preprocess_input_text(raw_text)
    if len(text.split()) < 3:
        return render_template(
            "index.html",
            result="Input is too short after preprocessing. Please enter a longer review.",
        )

    features_df = transform_text_to_features(text)
    result = model.predict(features_df)
    prediction = result[0]

    PREDICTION_COUNT.labels(prediction=str(prediction)).inc()
    REQUEST_LATENCY.labels(endpoint="/predict").observe(time.time() - start_time)

    return render_template("index.html", result=prediction)


@app.route("/metrics", methods=["GET"])
def metrics():
    """Expose only custom Prometheus metrics."""
    return generate_latest(registry), 200, {"Content-Type": CONTENT_TYPE_LATEST}


if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)
